version: "3"
services:
  pg:
    image: "postgres:12"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  node_backend:
    depends_on:
      - pg
    container_name: "node_backend"
    build: .
    entrypoint: ["./wait-for-it.sh", "-t", "30", "pg:${DB_PORT}", "--", "./docker-entrypoint.sh"]
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ./docker-entrypoint.sh:/usr/src/app/docker-entrypoint.sh
