# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
        ports:
        - 5432:5432

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: Make environment file
      uses: SpicyPizza/create-envfile@v1
      with:
        NODE_ENV: "test"
        NODE_PORT: "3001"
        NODE_HOST: "0.0.0.0"
        HOST_ADDRESS: "http://localhost:3001"
        DB_HOST: "postgres"
        TEST_DB_HOST: "postgres"
        DB_PORT: "5432"
        TEST_DB_PORT: "5432"
        DB_NAME: ${{ secrets.DB_NAME }}
        TEST_DB_NAME: ${{ secrets.DB_NAME }}
        DB_DIALECT: "postgres"
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        COOKIE_SECRET: "substratestartkitapp"
        COOKIE_DOMAIN: "localhost"
        COOKIE_HTTP_ONLY: false
        COOKIE_SECURE: false
        COOKIE_NAME: substratestartkitapp.sid
        SESSION_TABLE: session
        GITHUB_APP_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_APP_CLIENT_ID }}
        GITHUB_APP_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_APP_CLIENT_SECRET }}
        GITHUB_API_URL: "https://api.github.com/"
        GITHUB_LOGIN_SUCCESS_REDIRECT_URL: "http://localhost:3000/#/github/success"
        GITHUB_LOGIN_ERROR_REDIRECT_URL: "http://localhost:3000/#/github/error"
    - name: Build code
      run: |
        yarn
        yarn build
    - name: Run unit tests
      run: |
        yarn test:unit
    - name: Run integration tests
      run: |
        yarn test:integration
